version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      development:
        patterns:
          - "@types/*"
          - "typescript"
          - "@biomejs/biome"
          - "vitest"
      production:
        patterns:
          - "*"
        exclude-patterns:
          - "@types/*"
          - "typescript"
          - "@biomejs/biome"
          - "vitest"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"