name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: bun install
      
      - name: Run tests
        run: bun run typecheck && bun run lint:check
      
      - name: Build project
        run: bun run build
      
      - name: Package release
        run: |
          tar -czf mcp-ai-memory-${{ github.ref_name }}.tar.gz \
            dist/ \
            package.json \
            README.md \
            LICENSE \
            .env.example
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: mcp-ai-memory-${{ github.ref_name }}.tar.gz
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}